apiVersion: v1
kind: Service
metadata:
  name: weather-app
  namespace: weather-app-ns
spec:
  type: NodePort
  selector:
    app: weather-app
  ports:
    - protocol: TCP
      targetPort: 5000
      nodePort: 5000
